// Code generated by "stringer -type MembershipChangeMode ."; DO NOT EDIT

package raft

import "fmt"

const _MembershipChangeMode_name = "StableProposedJointConsensusProposedFinalConsensus"

var _MembershipChangeMode_index = [...]uint8{0, 6, 28, 50}

func (i MembershipChangeMode) String() string {
	if i < 0 || i >= MembershipChangeMode(len(_MembershipChangeMode_index)-1) {
		return fmt.Sprintf("MembershipChangeMode(%d)", i)
	}
	return _MembershipChangeMode_name[_MembershipChangeMode_index[i]:_MembershipChangeMode_index[i+1]]
}
