// Code generated by protoc-gen-go.
// source: nodelist.proto
// DO NOT EDIT!

/*
Package raft is a generated protocol buffer package.

It is generated from these files:
	nodelist.proto

It has these top-level messages:
	NodePb
	NodeListPb
*/
package raft

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type NodePb struct {
	NodeId           *uint64 `protobuf:"fixed64,1,req,name=nodeId" json:"nodeId,omitempty"`
	Address          *string `protobuf:"bytes,2,req,name=address" json:"address,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NodePb) Reset()         { *m = NodePb{} }
func (m *NodePb) String() string { return proto.CompactTextString(m) }
func (*NodePb) ProtoMessage()    {}

func (m *NodePb) GetNodeId() uint64 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

func (m *NodePb) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

type NodeListPb struct {
	Current          []*NodePb `protobuf:"bytes,1,rep,name=current" json:"current,omitempty"`
	Next             []*NodePb `protobuf:"bytes,2,rep,name=next" json:"next,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *NodeListPb) Reset()         { *m = NodeListPb{} }
func (m *NodeListPb) String() string { return proto.CompactTextString(m) }
func (*NodeListPb) ProtoMessage()    {}

func (m *NodeListPb) GetCurrent() []*NodePb {
	if m != nil {
		return m.Current
	}
	return nil
}

func (m *NodeListPb) GetNext() []*NodePb {
	if m != nil {
		return m.Next
	}
	return nil
}
