// Code generated by protoc-gen-go.
// source: webhookconfig.proto
// DO NOT EDIT!

/*
Package hooks is a generated protocol buffer package.

It is generated from these files:
	webhookconfig.proto

It has these top-level messages:
	WebHookPb
	WebHookConfigPb
*/
package hooks

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type WebHookPb struct {
	Url              *string `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WebHookPb) Reset()         { *m = WebHookPb{} }
func (m *WebHookPb) String() string { return proto.CompactTextString(m) }
func (*WebHookPb) ProtoMessage()    {}

func (m *WebHookPb) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

type WebHookConfigPb struct {
	Hooks            []*WebHookPb `protobuf:"bytes,1,rep,name=hooks" json:"hooks,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *WebHookConfigPb) Reset()         { *m = WebHookConfigPb{} }
func (m *WebHookConfigPb) String() string { return proto.CompactTextString(m) }
func (*WebHookConfigPb) ProtoMessage()    {}

func (m *WebHookConfigPb) GetHooks() []*WebHookPb {
	if m != nil {
		return m.Hooks
	}
	return nil
}
