// Code generated by protoc-gen-go.
// source: discovery.proto
// DO NOT EDIT!

/*
Package discovery is a generated protocol buffer package.

It is generated from these files:
	discovery.proto

It has these top-level messages:
	NodePb
	NodeListPb
	NodeConfigPb
*/
package discovery

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type NodePb struct {
	Id               *uint64 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Address          *string `protobuf:"bytes,2,req,name=address" json:"address,omitempty"`
	State            *int32  `protobuf:"varint,3,req,name=state" json:"state,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NodePb) Reset()         { *m = NodePb{} }
func (m *NodePb) String() string { return proto.CompactTextString(m) }
func (*NodePb) ProtoMessage()    {}

func (m *NodePb) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *NodePb) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *NodePb) GetState() int32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

type NodeListPb struct {
	New              []*NodePb `protobuf:"bytes,1,rep,name=new" json:"new,omitempty"`
	Old              []*NodePb `protobuf:"bytes,2,rep,name=old" json:"old,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *NodeListPb) Reset()         { *m = NodeListPb{} }
func (m *NodeListPb) String() string { return proto.CompactTextString(m) }
func (*NodeListPb) ProtoMessage()    {}

func (m *NodeListPb) GetNew() []*NodePb {
	if m != nil {
		return m.New
	}
	return nil
}

func (m *NodeListPb) GetOld() []*NodePb {
	if m != nil {
		return m.Old
	}
	return nil
}

type NodeConfigPb struct {
	Current          *NodeListPb `protobuf:"bytes,1,req,name=current" json:"current,omitempty"`
	Previous         *NodeListPb `protobuf:"bytes,2,opt,name=previous" json:"previous,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *NodeConfigPb) Reset()         { *m = NodeConfigPb{} }
func (m *NodeConfigPb) String() string { return proto.CompactTextString(m) }
func (*NodeConfigPb) ProtoMessage()    {}

func (m *NodeConfigPb) GetCurrent() *NodeListPb {
	if m != nil {
		return m.Current
	}
	return nil
}

func (m *NodeConfigPb) GetPrevious() *NodeListPb {
	if m != nil {
		return m.Previous
	}
	return nil
}
