// Code generated by protoc-gen-go.
// source: discovery.proto
// DO NOT EDIT!

/*
Package discovery is a generated protocol buffer package.

It is generated from these files:
	discovery.proto

It has these top-level messages:
	NodeListPb
	NodeConfigPb
*/
package discovery

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type NodeListPb struct {
	New              []string `protobuf:"bytes,1,rep,name=new" json:"new,omitempty"`
	Old              []string `protobuf:"bytes,2,rep,name=old" json:"old,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *NodeListPb) Reset()         { *m = NodeListPb{} }
func (m *NodeListPb) String() string { return proto.CompactTextString(m) }
func (*NodeListPb) ProtoMessage()    {}

func (m *NodeListPb) GetNew() []string {
	if m != nil {
		return m.New
	}
	return nil
}

func (m *NodeListPb) GetOld() []string {
	if m != nil {
		return m.Old
	}
	return nil
}

type NodeConfigPb struct {
	Current          *NodeListPb `protobuf:"bytes,1,req,name=current" json:"current,omitempty"`
	Previous         *NodeListPb `protobuf:"bytes,2,opt,name=previous" json:"previous,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *NodeConfigPb) Reset()         { *m = NodeConfigPb{} }
func (m *NodeConfigPb) String() string { return proto.CompactTextString(m) }
func (*NodeConfigPb) ProtoMessage()    {}

func (m *NodeConfigPb) GetCurrent() *NodeListPb {
	if m != nil {
		return m.Current
	}
	return nil
}

func (m *NodeConfigPb) GetPrevious() *NodeListPb {
	if m != nil {
		return m.Previous
	}
	return nil
}
