// Code generated by protoc-gen-go.
// source: commands.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	commands.proto

It has these top-level messages:
	AgentCommand
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type AgentCommand struct {
	Command          *string `protobuf:"bytes,1,req,name=command" json:"command,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Tenant           []byte  `protobuf:"bytes,3,opt,name=tenant" json:"tenant,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AgentCommand) Reset()         { *m = AgentCommand{} }
func (m *AgentCommand) String() string { return proto.CompactTextString(m) }
func (*AgentCommand) ProtoMessage()    {}

func (m *AgentCommand) GetCommand() string {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return ""
}

func (m *AgentCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *AgentCommand) GetTenant() []byte {
	if m != nil {
		return m.Tenant
	}
	return nil
}
