// Code generated by protoc-gen-go.
// source: auth.proto
// DO NOT EDIT!

package protobufs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type UserPb struct {
	User             *string `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
	Salt             []byte  `protobuf:"bytes,2,req,name=salt" json:"salt,omitempty"`
	Password         []byte  `protobuf:"bytes,3,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserPb) Reset()                    { *m = UserPb{} }
func (m *UserPb) String() string            { return proto.CompactTextString(m) }
func (*UserPb) ProtoMessage()               {}
func (*UserPb) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *UserPb) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *UserPb) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *UserPb) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

type UserTablePb struct {
	Users            []*UserPb `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *UserTablePb) Reset()                    { *m = UserTablePb{} }
func (m *UserTablePb) String() string            { return proto.CompactTextString(m) }
func (*UserTablePb) ProtoMessage()               {}
func (*UserTablePb) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *UserTablePb) GetUsers() []*UserPb {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*UserPb)(nil), "protobufs.UserPb")
	proto.RegisterType((*UserTablePb)(nil), "protobufs.UserTablePb")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0x53, 0x49, 0xa5, 0x69, 0xc5, 0x4a, 0x66,
	0x5c, 0x6c, 0xa1, 0xc5, 0xa9, 0x45, 0x01, 0x49, 0x42, 0x3c, 0x5c, 0x2c, 0xa5, 0x40, 0x96, 0x04,
	0xa3, 0x02, 0x93, 0x06, 0x27, 0x88, 0x57, 0x9c, 0x98, 0x53, 0x22, 0xc1, 0x04, 0xe4, 0xf1, 0x08,
	0x09, 0x70, 0x71, 0x14, 0x24, 0x16, 0x17, 0x97, 0xe7, 0x17, 0xa5, 0x48, 0x30, 0x83, 0x44, 0x94,
	0xf4, 0xb9, 0xb8, 0x41, 0xfa, 0x42, 0x12, 0x93, 0x72, 0x52, 0x81, 0x9a, 0x15, 0xb8, 0x58, 0x41,
	0x9a, 0x8b, 0x81, 0xba, 0x99, 0x35, 0xb8, 0x8d, 0x04, 0xf5, 0xe0, 0x36, 0xe8, 0x41, 0x8c, 0x07,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x81, 0xfd, 0xac, 0x80, 0x00, 0x00, 0x00,
}
