// Code generated by protoc-gen-go.
// source: communication.proto
// DO NOT EDIT!

package protobufs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type VoteRequestPb struct {
	Term             *uint64 `protobuf:"varint,1,req,name=term" json:"term,omitempty"`
	CandidateId      *uint64 `protobuf:"fixed64,2,req,name=candidateId" json:"candidateId,omitempty"`
	LastLogIndex     *uint64 `protobuf:"varint,3,req,name=lastLogIndex" json:"lastLogIndex,omitempty"`
	LastLogTerm      *uint64 `protobuf:"varint,4,req,name=lastLogTerm" json:"lastLogTerm,omitempty"`
	ClusterId        *uint64 `protobuf:"fixed64,5,req,name=clusterId" json:"clusterId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *VoteRequestPb) Reset()                    { *m = VoteRequestPb{} }
func (m *VoteRequestPb) String() string            { return proto.CompactTextString(m) }
func (*VoteRequestPb) ProtoMessage()               {}
func (*VoteRequestPb) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *VoteRequestPb) GetTerm() uint64 {
	if m != nil && m.Term != nil {
		return *m.Term
	}
	return 0
}

func (m *VoteRequestPb) GetCandidateId() uint64 {
	if m != nil && m.CandidateId != nil {
		return *m.CandidateId
	}
	return 0
}

func (m *VoteRequestPb) GetLastLogIndex() uint64 {
	if m != nil && m.LastLogIndex != nil {
		return *m.LastLogIndex
	}
	return 0
}

func (m *VoteRequestPb) GetLastLogTerm() uint64 {
	if m != nil && m.LastLogTerm != nil {
		return *m.LastLogTerm
	}
	return 0
}

func (m *VoteRequestPb) GetClusterId() uint64 {
	if m != nil && m.ClusterId != nil {
		return *m.ClusterId
	}
	return 0
}

type VoteResponsePb struct {
	NodeId           *uint64 `protobuf:"fixed64,1,req,name=nodeId" json:"nodeId,omitempty"`
	Term             *uint64 `protobuf:"varint,2,req,name=term" json:"term,omitempty"`
	VoteGranted      *bool   `protobuf:"varint,3,req,name=voteGranted" json:"voteGranted,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *VoteResponsePb) Reset()                    { *m = VoteResponsePb{} }
func (m *VoteResponsePb) String() string            { return proto.CompactTextString(m) }
func (*VoteResponsePb) ProtoMessage()               {}
func (*VoteResponsePb) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *VoteResponsePb) GetNodeId() uint64 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

func (m *VoteResponsePb) GetTerm() uint64 {
	if m != nil && m.Term != nil {
		return *m.Term
	}
	return 0
}

func (m *VoteResponsePb) GetVoteGranted() bool {
	if m != nil && m.VoteGranted != nil {
		return *m.VoteGranted
	}
	return false
}

type AppendRequestPb struct {
	Term             *uint64    `protobuf:"varint,1,req,name=term" json:"term,omitempty"`
	LeaderId         *uint64    `protobuf:"fixed64,2,req,name=leaderId" json:"leaderId,omitempty"`
	PrevLogIndex     *uint64    `protobuf:"varint,3,req,name=prevLogIndex" json:"prevLogIndex,omitempty"`
	PrevLogTerm      *uint64    `protobuf:"varint,4,req,name=prevLogTerm" json:"prevLogTerm,omitempty"`
	LeaderCommit     *uint64    `protobuf:"varint,5,req,name=leaderCommit" json:"leaderCommit,omitempty"`
	Entries          []*EntryPb `protobuf:"bytes,6,rep,name=entries" json:"entries,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *AppendRequestPb) Reset()                    { *m = AppendRequestPb{} }
func (m *AppendRequestPb) String() string            { return proto.CompactTextString(m) }
func (*AppendRequestPb) ProtoMessage()               {}
func (*AppendRequestPb) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *AppendRequestPb) GetTerm() uint64 {
	if m != nil && m.Term != nil {
		return *m.Term
	}
	return 0
}

func (m *AppendRequestPb) GetLeaderId() uint64 {
	if m != nil && m.LeaderId != nil {
		return *m.LeaderId
	}
	return 0
}

func (m *AppendRequestPb) GetPrevLogIndex() uint64 {
	if m != nil && m.PrevLogIndex != nil {
		return *m.PrevLogIndex
	}
	return 0
}

func (m *AppendRequestPb) GetPrevLogTerm() uint64 {
	if m != nil && m.PrevLogTerm != nil {
		return *m.PrevLogTerm
	}
	return 0
}

func (m *AppendRequestPb) GetLeaderCommit() uint64 {
	if m != nil && m.LeaderCommit != nil {
		return *m.LeaderCommit
	}
	return 0
}

func (m *AppendRequestPb) GetEntries() []*EntryPb {
	if m != nil {
		return m.Entries
	}
	return nil
}

type JoinRequestPb struct {
	ClusterId        *uint64    `protobuf:"fixed64,1,req,name=clusterId" json:"clusterId,omitempty"`
	Last             *bool      `protobuf:"varint,2,opt,name=last" json:"last,omitempty"`
	Entries          []*EntryPb `protobuf:"bytes,3,rep,name=entries" json:"entries,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *JoinRequestPb) Reset()                    { *m = JoinRequestPb{} }
func (m *JoinRequestPb) String() string            { return proto.CompactTextString(m) }
func (*JoinRequestPb) ProtoMessage()               {}
func (*JoinRequestPb) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *JoinRequestPb) GetClusterId() uint64 {
	if m != nil && m.ClusterId != nil {
		return *m.ClusterId
	}
	return 0
}

func (m *JoinRequestPb) GetLast() bool {
	if m != nil && m.Last != nil {
		return *m.Last
	}
	return false
}

func (m *JoinRequestPb) GetEntries() []*EntryPb {
	if m != nil {
		return m.Entries
	}
	return nil
}

type AppendResponsePb struct {
	Term             *uint64 `protobuf:"varint,1,req,name=term" json:"term,omitempty"`
	Success          *bool   `protobuf:"varint,2,req,name=success" json:"success,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AppendResponsePb) Reset()                    { *m = AppendResponsePb{} }
func (m *AppendResponsePb) String() string            { return proto.CompactTextString(m) }
func (*AppendResponsePb) ProtoMessage()               {}
func (*AppendResponsePb) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *AppendResponsePb) GetTerm() uint64 {
	if m != nil && m.Term != nil {
		return *m.Term
	}
	return 0
}

func (m *AppendResponsePb) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

type ProposalResponsePb struct {
	NewIndex         *uint64 `protobuf:"varint,1,req,name=newIndex" json:"newIndex,omitempty"`
	Error            *string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProposalResponsePb) Reset()                    { *m = ProposalResponsePb{} }
func (m *ProposalResponsePb) String() string            { return proto.CompactTextString(m) }
func (*ProposalResponsePb) ProtoMessage()               {}
func (*ProposalResponsePb) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ProposalResponsePb) GetNewIndex() uint64 {
	if m != nil && m.NewIndex != nil {
		return *m.NewIndex
	}
	return 0
}

func (m *ProposalResponsePb) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type DiscoveryResponsePb struct {
	NodeId           *uint64 `protobuf:"fixed64,1,req,name=nodeId" json:"nodeId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DiscoveryResponsePb) Reset()                    { *m = DiscoveryResponsePb{} }
func (m *DiscoveryResponsePb) String() string            { return proto.CompactTextString(m) }
func (*DiscoveryResponsePb) ProtoMessage()               {}
func (*DiscoveryResponsePb) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *DiscoveryResponsePb) GetNodeId() uint64 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

func init() {
	proto.RegisterType((*VoteRequestPb)(nil), "protobufs.VoteRequestPb")
	proto.RegisterType((*VoteResponsePb)(nil), "protobufs.VoteResponsePb")
	proto.RegisterType((*AppendRequestPb)(nil), "protobufs.AppendRequestPb")
	proto.RegisterType((*JoinRequestPb)(nil), "protobufs.JoinRequestPb")
	proto.RegisterType((*AppendResponsePb)(nil), "protobufs.AppendResponsePb")
	proto.RegisterType((*ProposalResponsePb)(nil), "protobufs.ProposalResponsePb")
	proto.RegisterType((*DiscoveryResponsePb)(nil), "protobufs.DiscoveryResponsePb")
}

func init() { proto.RegisterFile("communication.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x6b, 0x2a, 0x31,
	0x14, 0xc5, 0x19, 0x1d, 0x75, 0xbc, 0xfe, 0x7d, 0xf1, 0x2d, 0x86, 0xb7, 0x92, 0x79, 0x3c, 0x70,
	0x25, 0xbc, 0x42, 0x3f, 0x40, 0xb1, 0xa5, 0x58, 0xba, 0x90, 0xd2, 0x76, 0x1f, 0x93, 0xdb, 0x12,
	0x18, 0x93, 0x34, 0xc9, 0xd8, 0xfa, 0x49, 0xfa, 0x75, 0x9b, 0x89, 0xce, 0x54, 0x29, 0xae, 0x06,
	0xee, 0xcd, 0x39, 0xf7, 0x77, 0xce, 0xc0, 0x84, 0xa9, 0xcd, 0xa6, 0x90, 0x82, 0x51, 0x27, 0x94,
	0x9c, 0x6b, 0xa3, 0x9c, 0x22, 0xdd, 0xf0, 0x59, 0x17, 0x2f, 0xf6, 0x4f, 0xbf, 0xdc, 0x57, 0x8b,
	0x4c, 0xc3, 0xe0, 0x59, 0x39, 0x7c, 0xc0, 0xb7, 0x02, 0xad, 0x5b, 0xad, 0x49, 0x1f, 0x62, 0x87,
	0x66, 0x93, 0x46, 0xd3, 0xc6, 0x2c, 0x26, 0x13, 0xe8, 0x31, 0x2a, 0xb9, 0xe0, 0xd4, 0xe1, 0x92,
	0xa7, 0x0d, 0x3f, 0x6c, 0x93, 0xdf, 0xd0, 0xcf, 0xa9, 0x75, 0xf7, 0xea, 0x75, 0x29, 0x39, 0x7e,
	0xa4, 0xcd, 0xea, 0xe9, 0x61, 0xfa, 0x58, 0xea, 0xe3, 0x30, 0xfc, 0x05, 0x5d, 0x96, 0x17, 0xd6,
	0x3b, 0x7a, 0x75, 0xab, 0x54, 0x67, 0x0b, 0x18, 0xee, 0x2f, 0x5a, 0xad, 0xa4, 0x45, 0x7f, 0x72,
	0x08, 0x6d, 0xa9, 0x78, 0xe9, 0x1f, 0x05, 0xff, 0x0a, 0xa1, 0x51, 0xf9, 0x6e, 0xfd, 0xfb, 0x5b,
	0x43, 0xa5, 0x43, 0x1e, 0x8e, 0x25, 0xd9, 0x67, 0x04, 0xa3, 0x2b, 0xad, 0x51, 0xf2, 0x73, 0xe4,
	0x63, 0x48, 0x72, 0xa4, 0x3c, 0x1c, 0xae, 0xb1, 0xb5, 0xc1, 0xed, 0x4f, 0xec, 0xc3, 0xf4, 0x08,
	0xbb, 0x4c, 0x18, 0xc4, 0x0b, 0xdf, 0x95, 0x70, 0x81, 0x3c, 0x26, 0x7f, 0xa1, 0x83, 0xd2, 0x19,
	0x81, 0x36, 0x6d, 0x4f, 0x9b, 0xb3, 0xde, 0x05, 0x99, 0xd7, 0xb5, 0xce, 0x6f, 0xfc, 0x66, 0xb7,
	0x5a, 0x67, 0x4f, 0x30, 0xb8, 0x53, 0x42, 0x7e, 0x63, 0x9d, 0x54, 0x50, 0x07, 0x2c, 0xab, 0xf2,
	0x5c, 0xd1, 0x2c, 0x39, 0xb6, 0x6d, 0x9e, 0xb5, 0xfd, 0x0f, 0xe3, 0x2a, 0x6f, 0xdd, 0xdb, 0x69,
	0xe0, 0x11, 0x74, 0x6c, 0xc1, 0x18, 0x5a, 0x1b, 0xf2, 0x26, 0xd9, 0x25, 0x90, 0x95, 0x51, 0x5a,
	0x59, 0x9a, 0x1f, 0x89, 0x7c, 0x2f, 0x12, 0xdf, 0xf7, 0x0d, 0xec, 0x85, 0x03, 0x68, 0xa1, 0x31,
	0xca, 0x04, 0x9c, 0x6e, 0xf6, 0x0f, 0x26, 0xd7, 0xc2, 0x32, 0xb5, 0x45, 0xb3, 0x3b, 0xff, 0x93,
	0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x65, 0x12, 0x27, 0x67, 0x02, 0x00, 0x00,
}
