// Code generated by protoc-gen-go.
// source: communication.proto
// DO NOT EDIT!

package protobufs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type VoteRequestPb struct {
	Term             *uint64 `protobuf:"varint,1,req,name=term" json:"term,omitempty"`
	CandidateId      *uint64 `protobuf:"fixed64,2,req,name=candidateId" json:"candidateId,omitempty"`
	LastLogIndex     *uint64 `protobuf:"varint,3,req,name=lastLogIndex" json:"lastLogIndex,omitempty"`
	LastLogTerm      *uint64 `protobuf:"varint,4,req,name=lastLogTerm" json:"lastLogTerm,omitempty"`
	ClusterId        *uint64 `protobuf:"fixed64,5,req,name=clusterId" json:"clusterId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *VoteRequestPb) Reset()                    { *m = VoteRequestPb{} }
func (m *VoteRequestPb) String() string            { return proto.CompactTextString(m) }
func (*VoteRequestPb) ProtoMessage()               {}
func (*VoteRequestPb) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *VoteRequestPb) GetTerm() uint64 {
	if m != nil && m.Term != nil {
		return *m.Term
	}
	return 0
}

func (m *VoteRequestPb) GetCandidateId() uint64 {
	if m != nil && m.CandidateId != nil {
		return *m.CandidateId
	}
	return 0
}

func (m *VoteRequestPb) GetLastLogIndex() uint64 {
	if m != nil && m.LastLogIndex != nil {
		return *m.LastLogIndex
	}
	return 0
}

func (m *VoteRequestPb) GetLastLogTerm() uint64 {
	if m != nil && m.LastLogTerm != nil {
		return *m.LastLogTerm
	}
	return 0
}

func (m *VoteRequestPb) GetClusterId() uint64 {
	if m != nil && m.ClusterId != nil {
		return *m.ClusterId
	}
	return 0
}

type VoteResponsePb struct {
	NodeId           *uint64 `protobuf:"fixed64,1,req,name=nodeId" json:"nodeId,omitempty"`
	Term             *uint64 `protobuf:"varint,2,req,name=term" json:"term,omitempty"`
	VoteGranted      *bool   `protobuf:"varint,3,req,name=voteGranted" json:"voteGranted,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *VoteResponsePb) Reset()                    { *m = VoteResponsePb{} }
func (m *VoteResponsePb) String() string            { return proto.CompactTextString(m) }
func (*VoteResponsePb) ProtoMessage()               {}
func (*VoteResponsePb) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *VoteResponsePb) GetNodeId() uint64 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

func (m *VoteResponsePb) GetTerm() uint64 {
	if m != nil && m.Term != nil {
		return *m.Term
	}
	return 0
}

func (m *VoteResponsePb) GetVoteGranted() bool {
	if m != nil && m.VoteGranted != nil {
		return *m.VoteGranted
	}
	return false
}

type AppendRequestPb struct {
	Term             *uint64    `protobuf:"varint,1,req,name=term" json:"term,omitempty"`
	LeaderId         *uint64    `protobuf:"fixed64,2,req,name=leaderId" json:"leaderId,omitempty"`
	PrevLogIndex     *uint64    `protobuf:"varint,3,req,name=prevLogIndex" json:"prevLogIndex,omitempty"`
	PrevLogTerm      *uint64    `protobuf:"varint,4,req,name=prevLogTerm" json:"prevLogTerm,omitempty"`
	LeaderCommit     *uint64    `protobuf:"varint,5,req,name=leaderCommit" json:"leaderCommit,omitempty"`
	Entries          []*EntryPb `protobuf:"bytes,6,rep,name=entries" json:"entries,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *AppendRequestPb) Reset()                    { *m = AppendRequestPb{} }
func (m *AppendRequestPb) String() string            { return proto.CompactTextString(m) }
func (*AppendRequestPb) ProtoMessage()               {}
func (*AppendRequestPb) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *AppendRequestPb) GetTerm() uint64 {
	if m != nil && m.Term != nil {
		return *m.Term
	}
	return 0
}

func (m *AppendRequestPb) GetLeaderId() uint64 {
	if m != nil && m.LeaderId != nil {
		return *m.LeaderId
	}
	return 0
}

func (m *AppendRequestPb) GetPrevLogIndex() uint64 {
	if m != nil && m.PrevLogIndex != nil {
		return *m.PrevLogIndex
	}
	return 0
}

func (m *AppendRequestPb) GetPrevLogTerm() uint64 {
	if m != nil && m.PrevLogTerm != nil {
		return *m.PrevLogTerm
	}
	return 0
}

func (m *AppendRequestPb) GetLeaderCommit() uint64 {
	if m != nil && m.LeaderCommit != nil {
		return *m.LeaderCommit
	}
	return 0
}

func (m *AppendRequestPb) GetEntries() []*EntryPb {
	if m != nil {
		return m.Entries
	}
	return nil
}

type JoinRequestPb struct {
	ClusterId        *uint64    `protobuf:"fixed64,1,req,name=clusterId" json:"clusterId,omitempty"`
	Last             *bool      `protobuf:"varint,2,opt,name=last" json:"last,omitempty"`
	Entries          []*EntryPb `protobuf:"bytes,3,rep,name=entries" json:"entries,omitempty"`
	ConfigEntries    []*EntryPb `protobuf:"bytes,4,rep,name=configEntries" json:"configEntries,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *JoinRequestPb) Reset()                    { *m = JoinRequestPb{} }
func (m *JoinRequestPb) String() string            { return proto.CompactTextString(m) }
func (*JoinRequestPb) ProtoMessage()               {}
func (*JoinRequestPb) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *JoinRequestPb) GetClusterId() uint64 {
	if m != nil && m.ClusterId != nil {
		return *m.ClusterId
	}
	return 0
}

func (m *JoinRequestPb) GetLast() bool {
	if m != nil && m.Last != nil {
		return *m.Last
	}
	return false
}

func (m *JoinRequestPb) GetEntries() []*EntryPb {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *JoinRequestPb) GetConfigEntries() []*EntryPb {
	if m != nil {
		return m.ConfigEntries
	}
	return nil
}

type AppendResponsePb struct {
	Term             *uint64 `protobuf:"varint,1,req,name=term" json:"term,omitempty"`
	Success          *bool   `protobuf:"varint,2,req,name=success" json:"success,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AppendResponsePb) Reset()                    { *m = AppendResponsePb{} }
func (m *AppendResponsePb) String() string            { return proto.CompactTextString(m) }
func (*AppendResponsePb) ProtoMessage()               {}
func (*AppendResponsePb) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *AppendResponsePb) GetTerm() uint64 {
	if m != nil && m.Term != nil {
		return *m.Term
	}
	return 0
}

func (m *AppendResponsePb) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

type ProposalResponsePb struct {
	NewIndex         *uint64 `protobuf:"varint,1,req,name=newIndex" json:"newIndex,omitempty"`
	Error            *string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProposalResponsePb) Reset()                    { *m = ProposalResponsePb{} }
func (m *ProposalResponsePb) String() string            { return proto.CompactTextString(m) }
func (*ProposalResponsePb) ProtoMessage()               {}
func (*ProposalResponsePb) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ProposalResponsePb) GetNewIndex() uint64 {
	if m != nil && m.NewIndex != nil {
		return *m.NewIndex
	}
	return 0
}

func (m *ProposalResponsePb) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type DiscoveryResponsePb struct {
	NodeId           *uint64 `protobuf:"fixed64,1,req,name=nodeId" json:"nodeId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DiscoveryResponsePb) Reset()                    { *m = DiscoveryResponsePb{} }
func (m *DiscoveryResponsePb) String() string            { return proto.CompactTextString(m) }
func (*DiscoveryResponsePb) ProtoMessage()               {}
func (*DiscoveryResponsePb) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *DiscoveryResponsePb) GetNodeId() uint64 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

func init() {
	proto.RegisterType((*VoteRequestPb)(nil), "protobufs.VoteRequestPb")
	proto.RegisterType((*VoteResponsePb)(nil), "protobufs.VoteResponsePb")
	proto.RegisterType((*AppendRequestPb)(nil), "protobufs.AppendRequestPb")
	proto.RegisterType((*JoinRequestPb)(nil), "protobufs.JoinRequestPb")
	proto.RegisterType((*AppendResponsePb)(nil), "protobufs.AppendResponsePb")
	proto.RegisterType((*ProposalResponsePb)(nil), "protobufs.ProposalResponsePb")
	proto.RegisterType((*DiscoveryResponsePb)(nil), "protobufs.DiscoveryResponsePb")
}

func init() { proto.RegisterFile("communication.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x91, 0x51, 0x6b, 0xea, 0x30,
	0x14, 0xc7, 0xa9, 0x56, 0xad, 0x47, 0xab, 0xde, 0x78, 0x1f, 0xca, 0x7d, 0x92, 0x5e, 0x2e, 0x78,
	0x5f, 0x84, 0x0d, 0xf6, 0x01, 0x86, 0x93, 0xe1, 0xd8, 0x83, 0x8c, 0xb1, 0xf7, 0x9a, 0x1c, 0x25,
	0x50, 0x93, 0x2e, 0x49, 0xdd, 0x7c, 0xdb, 0xb7, 0xd8, 0xd7, 0x5d, 0x1a, 0x6d, 0xa7, 0x8c, 0x3e,
	0x15, 0x4e, 0xf2, 0xff, 0x9f, 0x5f, 0x7e, 0x85, 0x31, 0x95, 0xbb, 0x5d, 0x2e, 0x38, 0x4d, 0x0c,
	0x97, 0x62, 0x96, 0x29, 0x69, 0x24, 0xe9, 0xba, 0xcf, 0x3a, 0xdf, 0xe8, 0x3f, 0xfd, 0xe2, 0xbc,
	0x3c, 0x88, 0x33, 0x08, 0x5f, 0xa4, 0xc1, 0x27, 0x7c, 0xcd, 0x51, 0x9b, 0xd5, 0x9a, 0xf4, 0xc1,
	0x37, 0xa8, 0x76, 0x91, 0x37, 0x69, 0x4c, 0x7d, 0x32, 0x86, 0x1e, 0x4d, 0x04, 0xe3, 0x2c, 0x31,
	0xb8, 0x64, 0x51, 0xc3, 0x0e, 0xdb, 0xe4, 0x37, 0xf4, 0xd3, 0x44, 0x9b, 0x47, 0xb9, 0x5d, 0x0a,
	0x86, 0xef, 0x51, 0xb3, 0xbc, 0x7a, 0x9a, 0x3e, 0x17, 0x79, 0xdf, 0x0d, 0x7f, 0x41, 0x97, 0xa6,
	0xb9, 0xb6, 0x8d, 0x36, 0xdd, 0x2a, 0xd2, 0xf1, 0x1c, 0x06, 0xc7, 0x8d, 0x3a, 0x93, 0x42, 0xa3,
	0x5d, 0x39, 0x80, 0xb6, 0x90, 0xac, 0xe8, 0xf7, 0x5c, 0x7f, 0x89, 0xd0, 0x28, 0x7b, 0xf7, 0xf6,
	0xfe, 0xbd, 0x4a, 0x84, 0x41, 0xe6, 0x96, 0x05, 0xf1, 0xa7, 0x07, 0xc3, 0xdb, 0x2c, 0x43, 0xc1,
	0xea, 0xc8, 0x47, 0x10, 0xa4, 0x98, 0x30, 0xb7, 0xb8, 0xc2, 0xce, 0x14, 0xee, 0x7f, 0x62, 0x9f,
	0xa6, 0x67, 0xd8, 0xc5, 0x0b, 0x5d, 0x78, 0x6e, 0x5d, 0x71, 0xe3, 0xc8, 0x7d, 0xf2, 0x17, 0x3a,
	0x28, 0x8c, 0xe2, 0xa8, 0xa3, 0xf6, 0xa4, 0x39, 0xed, 0x5d, 0x93, 0x59, 0xa5, 0x75, 0xb6, 0xb0,
	0x27, 0x87, 0xd5, 0x3a, 0xfe, 0xf0, 0x20, 0x7c, 0x90, 0x5c, 0x7c, 0x73, 0x5d, 0x38, 0xa8, 0x5e,
	0x58, 0xb8, 0xb2, 0x60, 0xde, 0x34, 0x38, 0xef, 0x6d, 0xd6, 0xf5, 0x92, 0xff, 0x10, 0x52, 0x29,
	0x36, 0x7c, 0xbb, 0x38, 0x5d, 0xf5, 0x6b, 0x11, 0xae, 0x60, 0x54, 0xba, 0xa9, 0x1c, 0x5f, 0xca,
	0x19, 0x42, 0x47, 0xe7, 0x94, 0xa2, 0xd6, 0xce, 0x4d, 0x10, 0xdf, 0x00, 0x59, 0x29, 0x99, 0x49,
	0x9d, 0xa4, 0x67, 0x21, 0xeb, 0x50, 0xe0, 0xdb, 0xd1, 0xd6, 0x31, 0x18, 0x42, 0x0b, 0x95, 0x92,
	0xca, 0x91, 0x77, 0xe3, 0x7f, 0x30, 0xbe, 0xe3, 0x9a, 0xca, 0x3d, 0xaa, 0x43, 0xfd, 0x0f, 0xfd,
	0x0a, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xbd, 0xe4, 0x67, 0x93, 0x02, 0x00, 0x00,
}
