// Code generated by protoc-gen-go.
// source: config.proto
// DO NOT EDIT!

package protobufs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PurgeConfig struct {
	MinDuration      *int64  `protobuf:"varint,1,req,name=minDuration" json:"minDuration,omitempty"`
	MinRecords       *uint32 `protobuf:"varint,2,req,name=minRecords" json:"minRecords,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PurgeConfig) Reset()                    { *m = PurgeConfig{} }
func (m *PurgeConfig) String() string            { return proto.CompactTextString(m) }
func (*PurgeConfig) ProtoMessage()               {}
func (*PurgeConfig) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *PurgeConfig) GetMinDuration() int64 {
	if m != nil && m.MinDuration != nil {
		return *m.MinDuration
	}
	return 0
}

func (m *PurgeConfig) GetMinRecords() uint32 {
	if m != nil && m.MinRecords != nil {
		return *m.MinRecords
	}
	return 0
}

type ConfigPb struct {
	Purge            *PurgeConfig `protobuf:"bytes,1,opt,name=purge" json:"purge,omitempty"`
	HeartbeatTimeout *int64       `protobuf:"varint,2,req,name=heartbeatTimeout" json:"heartbeatTimeout,omitempty"`
	ElectionTimeout  *int64       `protobuf:"varint,3,req,name=electionTimeout" json:"electionTimeout,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ConfigPb) Reset()                    { *m = ConfigPb{} }
func (m *ConfigPb) String() string            { return proto.CompactTextString(m) }
func (*ConfigPb) ProtoMessage()               {}
func (*ConfigPb) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *ConfigPb) GetPurge() *PurgeConfig {
	if m != nil {
		return m.Purge
	}
	return nil
}

func (m *ConfigPb) GetHeartbeatTimeout() int64 {
	if m != nil && m.HeartbeatTimeout != nil {
		return *m.HeartbeatTimeout
	}
	return 0
}

func (m *ConfigPb) GetElectionTimeout() int64 {
	if m != nil && m.ElectionTimeout != nil {
		return *m.ElectionTimeout
	}
	return 0
}

func init() {
	proto.RegisterType((*PurgeConfig)(nil), "protobufs.PurgeConfig")
	proto.RegisterType((*ConfigPb)(nil), "protobufs.ConfigPb")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0x53, 0x49, 0xa5, 0x69, 0xc5,
	0x4a, 0x66, 0x5c, 0xdc, 0x01, 0xa5, 0x45, 0xe9, 0xa9, 0xce, 0x60, 0x79, 0x21, 0x61, 0x2e, 0xee,
	0xdc, 0xcc, 0x3c, 0x97, 0xd2, 0xa2, 0xc4, 0x92, 0xcc, 0xfc, 0x3c, 0x09, 0x46, 0x05, 0x26, 0x0d,
	0x66, 0x21, 0x21, 0x2e, 0x2e, 0xa0, 0x60, 0x50, 0x6a, 0x72, 0x7e, 0x51, 0x4a, 0xb1, 0x04, 0x13,
	0x50, 0x8c, 0x57, 0x29, 0x85, 0x8b, 0x03, 0xa2, 0x25, 0x20, 0x49, 0x48, 0x95, 0x8b, 0xb5, 0x00,
	0x64, 0x06, 0x50, 0x39, 0xa3, 0x06, 0xb7, 0x91, 0x98, 0x1e, 0xdc, 0x78, 0x3d, 0x64, 0xb3, 0x25,
	0xb8, 0x04, 0x32, 0x52, 0x13, 0x8b, 0x4a, 0x92, 0x52, 0x13, 0x4b, 0x42, 0x32, 0x73, 0x53, 0xf3,
	0x4b, 0x4b, 0xc0, 0x86, 0x31, 0x0b, 0x89, 0x73, 0xf1, 0xa7, 0xe6, 0xa4, 0x26, 0x83, 0xac, 0x84,
	0x49, 0x30, 0x83, 0x24, 0x00, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x9c, 0x6e, 0x64, 0xb7, 0x00,
	0x00, 0x00,
}
