// Code generated by protoc-gen-go.
// source: nodelist.proto
// DO NOT EDIT!

package protobufs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type NodePb struct {
	NodeId           *uint64 `protobuf:"fixed64,1,req,name=nodeId" json:"nodeId,omitempty"`
	Address          *string `protobuf:"bytes,2,req,name=address" json:"address,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NodePb) Reset()                    { *m = NodePb{} }
func (m *NodePb) String() string            { return proto.CompactTextString(m) }
func (*NodePb) ProtoMessage()               {}
func (*NodePb) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *NodePb) GetNodeId() uint64 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

func (m *NodePb) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

type NodeListPb struct {
	Current          []*NodePb `protobuf:"bytes,1,rep,name=current" json:"current,omitempty"`
	Next             []*NodePb `protobuf:"bytes,2,rep,name=next" json:"next,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *NodeListPb) Reset()                    { *m = NodeListPb{} }
func (m *NodeListPb) String() string            { return proto.CompactTextString(m) }
func (*NodeListPb) ProtoMessage()               {}
func (*NodeListPb) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *NodeListPb) GetCurrent() []*NodePb {
	if m != nil {
		return m.Current
	}
	return nil
}

func (m *NodeListPb) GetNext() []*NodePb {
	if m != nil {
		return m.Next
	}
	return nil
}

func init() {
	proto.RegisterType((*NodePb)(nil), "protobufs.NodePb")
	proto.RegisterType((*NodeListPb)(nil), "protobufs.NodeListPb")
}

func init() { proto.RegisterFile("nodelist.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0xcb, 0x4f, 0x49,
	0xcd, 0xc9, 0x2c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0x53, 0x49, 0xa5,
	0x69, 0xc5, 0x4a, 0x9a, 0x5c, 0x6c, 0x7e, 0x40, 0xc9, 0x80, 0x24, 0x21, 0x3e, 0x2e, 0x36, 0x90,
	0x32, 0xcf, 0x14, 0x09, 0x46, 0x05, 0x26, 0x0d, 0x36, 0x21, 0x7e, 0x2e, 0xf6, 0xc4, 0x94, 0x94,
	0xa2, 0xd4, 0xe2, 0x62, 0x09, 0x26, 0xa0, 0x00, 0xa7, 0x52, 0x20, 0x17, 0x17, 0x48, 0xa9, 0x0f,
	0xd0, 0x1c, 0xa0, 0x72, 0x25, 0x2e, 0xf6, 0xe4, 0xd2, 0xa2, 0xa2, 0xd4, 0xbc, 0x12, 0xa0, 0x7a,
	0x66, 0x0d, 0x6e, 0x23, 0x41, 0x3d, 0xb8, 0xa9, 0x7a, 0x50, 0x23, 0xe5, 0xb9, 0x58, 0xf2, 0x52,
	0x2b, 0x4a, 0x80, 0xfa, 0xb1, 0x2b, 0x00, 0x04, 0x00, 0x00, 0xff, 0xff, 0x03, 0x93, 0xc7, 0x0f,
	0x99, 0x00, 0x00, 0x00,
}
